language: node_js
node_js:
  - "4.2.3"
before_install:
  - npm install -g tsd
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: S47eRu6ZdNqKq+g3/fHHqODr+9agOk+rqaJ7i25Es8lZCFsAP4KpHbqLuKKC/mhCxKZ/ToWWWO8N03DkeOIgolpOzl1phfYECzI/Pkt7g0LLn1RIt+d+4U8XgBdqVkEsWHidKXj31Tgzp0Km1z2pNsJburI72hcdoHryXayGUNbpw8gHAUKiBha7wRz8dqC1msNWCkBxkwPcYZdVlnAIuAhX5OeFKpn0NNKJn8Ip9XizGfo/gulYdRxt2KtOpM22rAvD9RdU5PhWKPlb2+oVYV/K3IZx3KYE8lnLSrrQm9dCLuUCGKNs010HfFX5x9zwZNALzMhzW+KduHIXrghXBuVbTYxbDAE2QC/XoBcrza5p2E8mZyAGsFnWDCQhDHPiQB0rBJQqwITsKcvu73H5axxcD8KsxVX5hUStUEPSLz9tDLdA85/1nXuvzm6X6k2HD4f9jqA8KmOCiWBGkDe4CSMC1Qigt2E6thm1i82rMIkD67AvBP/NsU6xQaZHYm0Ol5Wc0oakYRvLaLZ+6+VaZiFt9tXz4wxTUkHbYI8OwXq5e1sASkWZcpAVCYK4amGBno+Q2M4qRMiofd4ewlF5G3eyzWF1q5YadArds92nGvWdj+tuymfo6zC2hWSKVN3pkshT8bcUyLRsqwQCDXJ5CDVvXiVQE18FpVEbUCyixig=
  on:
    tags: true
    repo: pushrocks/beautylog
notifications:
  slack:
    secure: VBAcnFNkROLEa0vrp0qu8rBC8OlOvxpnYwqv3NMIbLie3Cq1YS03DwhqX0YV1hEBiGqh5cBe3s3PxtY8LHF5QjB4/82nQJSUHdcUxPTLh9Eq6IZaKCnSEFhMKPbZw0TwULIlbLv1RV/te1+G+fVKguCn4+f5TqTRxntYErVQu/0ovDa9ln3vtlqhDg9lYk3FBFqOszbHL81Xr2KpDj2DN/15nRmxEGGpnhzQV44HZg/W93EaUqTyF+NCtStPCbpOKno0s89rYRXMosuP+1odpNcSouVqWscEZSNCIg1NTTLY0N8T51pX1g8Lw9Qz80OMRnn8D83mVvNNqLJx5vQ8THz96/L77Syih6a5Qr0AyE7hGcbNrfG+3LvomHDARQ9Tv2KqDcrkiTdh7NtXYiQogxdWYx9OzTUOau4z8K5tr9lLlqFa6WYkFFaoc/+49IFAkgoUXg65gTYUMkP76xu/MC0XEOTU2+jvXLyyTpacD7nWRcbrI8XG7oCvT3BUc/boe4DSIqCwgaffqDVxld+dnVju2xKHedRC/OwhKXMnrBqFSlF2OTn67yFjxeq5DKxzyfwBKv9ia9FPqADSPTqaRJuE4eydM6u4cTdU1+8yQJNaPk0NRMmhksH2vscwaAdxX3kyUxi7DrS8qxpg1FZCA34YSmXyk88Ov8ZNPBL82xI=
